# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 16:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import imagekit.models.fields
import testproj.utils.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cell',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='cell number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=testproj.utils.model_utils.UploadToPathAndRename('profile_images')),
        ),
    ]
